# -*- coding: utf-8 -*-
"""Language Detection-Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-7bg1dypCDb-xPIFeC35mZm-WZ8MCVc
"""

import pickle
import pandas as pd
from sklearn import metrics

# Load the trained model from the file
with open('/content/model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

print("Model loaded from 'model.pkl'.")

# Define a list of text samples in different languages for testing
texts = {
    'Arabic': [
        "مرحباً، كيف حالك اليوم؟",
        "أحب قراءة الكتب واستكشاف أماكن جديدة.",
        "كيف هو الطقس في مدينتك؟",
        "سألتقي بك في الحديقة غداً."
    ],
    'Danish': [
        "Hej, hvordan har du det i dag?",
        "Jeg elsker at læse bøger og udforske nye steder.",
        "Hvordan er vejret i din by?",
        "Kan du hjælpe mig med denne opgave?"
    ],
    'Dutch': [
        "Hallo, hoe gaat het vandaag?",
        "Ik hou van het lezen van boeken en het verkennen van nieuwe plaatsen.",
        "Hoe is het weer in jouw stad?",
        "Kun je me hiermee helpen?"
    ],
    'English': [
        "Hello, how are you today?",
        "I love reading books and exploring new places.",
        "What is the weather like in your city?",
        "Can you help me with this task?"
    ],
    'French': [
        "Bonjour, comment ça va aujourd'hui?",
        "J'aime lire des livres et explorer de nouveaux endroits.",
        "Quel temps fait-il dans votre ville?",
        "Pouvez-vous m'aider avec cette tâche?"
    ],
    'German': [
        "Hallo, wie geht es dir heute?",
        "Ich liebe es, Bücher zu lesen und neue Orte zu erkunden.",
        "Wie ist das Wetter in deiner Stadt?",
        "Kannst du mir dabei helfen?"
    ],
    'Greek': [
        "Γειά σου, πώς είσαι σήμερα;",
        "Μου αρέσει να διαβάζω βιβλία και να εξερευνώ νέα μέρη.",
        "Πώς είναι ο καιρός στην πόλη σου;",
        "Μπορείς να με βοηθήσεις με αυτήν την εργασία;"
    ],
    'Hindi': [
        "नमस्ते, आप कैसे हैं?",
        "मुझे किताबें पढ़ना और नई जगहें देखना पसंद है।",
        "आपके शहर में मौसम कैसा है?",
        "क्या आप मेरी मदद कर सकते हैं?"
    ],
    'Italian': [
        "Ciao, come stai oggi?",
        "Mi piace leggere libri ed esplorare nuovi luoghi.",
        "Com'è il tempo nella tua città?",
        "Puoi aiutarmi con questo compito?"
    ],
    'Kannada': [
        "ಹೇಗಿದ್ದೀರಾ, ನೀವು ಇಂದು ಹೇಗಿದ್ದೀರಿ?",
        "ನಾನು ಪುಸ್ತಕಗಳನ್ನು ಓದುವುದು ಮತ್ತು ಹೊಸ ಸ್ಥಳಗಳನ್ನು ಅನ್ವೇಷಿಸಲು ಇಷ್ಟಪಡುತ್ತೇನೆ.",
        "ನಿಮ್ಮ ನಗರದಲ್ಲಿ ಹವಾಮಾನ ಹೇಗಿದೆ?",
        "ನೀವು ನನ್ನಿಗೆ ಇದರಲ್ಲಿ ಸಹಾಯ ಮಾಡಬಹುದೆ?"
    ],
    'Malayalam': [
        "നിനക്ക് എങ്ങിനെ സുഖമാണോ?",
        "ഞാൻ പുസ്തകങ്ങൾ വായിക്കുക ഇഷ്ടപ്പെടുന്നു.",
        "നിന്റെ നഗരത്തിലെ കാലാവസ്ഥ എങ്ങിനെയാണ്?",
        "ഞാൻ നാളെ കൂട്ടുകാർക്കൊപ്പം പോകുന്നു."
    ],
    'Portugeese': [
        "Olá, como você está hoje?",
        "Eu adoro ler livros e explorar novos lugares.",
        "Como está o tempo na sua cidade?",
        "Você pode me ajudar com isso?"
    ],
    'Russian': [
        "Здравствуйте, как вы сегодня?",
        "Мне нравится читать книги и исследовать новые места.",
        "Какая погода в вашем городе?",
        "Можете помочь мне с этой задачей?"
    ],
    'Spanish': [
        "Hola, ¿cómo estás hoy?",
        "Me encanta leer libros y explorar nuevos lugares.",
        "¿Cómo está el clima en tu ciudad?",
        "¿Puedes ayudarme con esta tarea?"
    ],
    'Sweedish': [
        "Hej, hur mår du idag?",
        "Jag älskar att läsa böcker och utforska nya platser.",
        "Hur är vädret i din stad?",
        "Kan du hjälpa mig med det här?"
    ],
    'Tamil': [
        "வணக்கம், நீங்கள் எப்படி இருக்கிறீர்கள்?",
        "நான் புத்தகங்களைப் படிக்க மற்றும் புதிய இடங்களைத் தேட விரும்புகிறேன்.",
        "உங்கள் நகரத்தில் காலநிலை எப்படி உள்ளது?",
        "நான் நாளை உங்களை சந்திக்கிறேன்."
    ],
    'Turkish': [
        "Merhaba, bugün nasılsın?",
        "Kitap okumayı ve yeni yerler keşfetmeyi seviyorum.",
        "Şehrinizde hava durumu nasıl?",
        "Bana bu konuda yardım edebilir misin?"
    ]
}

# Flatten the text samples for predictions
flat_texts = [text for language_texts in texts.values() for text in language_texts]

# Create a list of actual labels (the correct language for each text)
actual_labels = [language for language, language_texts in texts.items() for _ in language_texts]

# Convert the list to a DataFrame
test_df = pd.DataFrame({'text': flat_texts, 'actual_language': actual_labels})

# Make predictions
predictions = loaded_model.predict(test_df['text'])

# Calculate accuracy
accuracy = metrics.accuracy_score(test_df['actual_language'], predictions)

# Print the predictions and the accuracy
for text, actual, prediction in zip(flat_texts, actual_labels, predictions):
    print(f"Text: '{text}'\nActual Language: {actual}\nPredicted Language: {prediction}\n")

# Print the overall accuracy
print(f"\nOverall Test Accuracy: {accuracy * 100:.2f}%")

